fix FTBS on XSERVER_LIBPCIACCESS
Not all Xserver versions define that symbol with a numeric value
(1 or 0), some just might not define it at all when disabled.

Using #if instead of #ifdef (as most sites do) will lead to compile break:

    ../../src/sis_driver.c:4008:25: error: expected value in expression
    #if XSERVER_LIBPCIACCESS
                            ^

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-sis/-/merge_requests/27>